name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: docker-latest
    env:
        app-name: docker_file.o

    steps:
    - uses: actions/checkout@v3
    - uses: mr-smithers-excellent/docker-build-push@v6
       with:
         image: docker-hub-repo/image-name
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
